#!/usr/bin/env bash

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
_SHA1=$3

perl -i.bak -ne 'print unless(m/^. Please enter the commit message/..m/^#$/)' "$COMMIT_MSG_FILE"

STORY_PREFIX="$(git symbolic-ref --short HEAD | grep -Eo 'sc-[0-9]+')"
if [[ "$STORY_PREFIX" -ne "" ]] && ! grep -q "$STORY_PREFIX" "$(head -n 1 "$COMMIT_MSG_FILE")"; then
  sed -i.bak "1s/^/\[$STORY_PREFIX\] /" "$COMMIT_MSG_FILE"
fi

SOB=$(git var GIT_COMMITTER_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
git interpret-trailers --in-place --trailer "$SOB" "$COMMIT_MSG_FILE"
if test "$COMMIT_SOURCE" = ""; then
  perl -i.bak -pe 'print "\n" if !$first_line++' "$COMMIT_MSG_FILE"
fi
