views:
  v1/pods:
    sortColumn: AGE:asc
    columns:
      - NAME
      - READY
      - STATUS
      - CPU
      - MEM
      - "%CPU/R"
      - "%MEM/R"
      - NAMESPACE
      - IP
      - NODE
  v1/nodes:
    columns:
      - NAME
      - STATUS
      - ROLES
      - TAINTS
      - VERSION
      - PODS
      - CPU
      - MEM
      - "%CPU"
      - "%MEM"
      - AGE
  v1/services:
    columns:
      - NAME
      - TYPE
      - PORT
      - AGE
