k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  headless: false
  logoless: true
  crumbsless: false
  readOnly: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 30
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: kubernetes-admin@k8s-services
  currentCluster: k8s-services
  clusters:
    k8s-services:
      namespace:
        active: monitoring
        lockFavorites: false
        favorites:
        - monitoring
        - auth
        - home-services
        - networking
        - dev-platform
        - kube-system
        - flux-system
        - all
        - default
      view:
        active: pods
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /tmp/k9s-screens-jake
