views:
  v1/pods:
    sortColumn: AGE:asc
    columns:
      - NAME
      - READY
      - STATUS
      - RESTARTS
      - CPU
      - MEM
      - "%CPU/R"
      - "%CPU/L"
      - "%MEM/R"
      - "%MEM/L"
      - AGE
  v1/services:
    columns:
      - NAME
      - TYPE
      - PORT
      - AGE
