views:
  v1/pods:
    columns:
      - AGE
      - NAME
      - STATUS
      - READY
  v1/services:
    columns:
      - AGE
      - NAMESPACE
      - NAME
      - TYPE
  v1/pvc:
    columns:
      - STORAGECLASS
      - NAME
      - CAPACITY
      - AGE
      - VOLUME
      - STATUS
      - NAMESPACE

