[package]
name = "starfield"
version = "0.1.0"
edition = "2024"

[dependencies]
pixels = { version = "0.13", features = ["winit"] }
winit = "0.28"
rand = "0.8"
wgpu = { version = "0.17", features = ["vulkan", "gl"] }
